name: C# Project Build and Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.100' # specify your .NET version

    - name: Restore dependencies
      run: dotnet restore csharpweb.csproj

    - name: Build
      run: dotnet build csharpweb.csproj --configuration Release --no-restore

    - name: Run
      run: dotnet run --project csharpweb.csproj
