name: C# Project with Selenium

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.100' # Replace with your .NET version

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1


      
    - name: Restore dependencies
      run: dotnet restore csharpweb.csproj

    - name: Build
      run: dotnet build csharpweb.csproj --configuration Release --no-restore

    - name: Run
      run: dotnet run --project csharpweb.csproj
